package errors

// Error Codes
const (
	STATUS_SUCCEED             = 200
	STATUS_RESSOURCE_GENERATED = 201
	STATUS_SUCCEED_NORETURN    = 204
	STATUS_INTERNAL_ERROR      = 500
	STATUS_NOT_DEVELOPED_YET   = 501
	STATUS_NO_RESOURCE_FOUND   = 404
	STATUS_METHOD_NOT_ALLOWED  = 405
	STATUS_NOT_AUTHORIZED      = 401
	STATUS_FARERPATH_ERROR     = 700
)

// farerpath Error Codes
const (
	FP_ALBUM_ALREADY_EXIST = "741"
	FP_ALREADY_LOGGED_IN   = "742"
	FP_VALUE_TOO_SHORT     = "743"
	FP_PASSWORD_NOT_MATCH  = "744"
	FP_ACCOUNT_NOT_EXIST   = "745"
	FP_VALUE_INVALID       = "746"
)
